### ISSUE TITLE
使用markdown写作时，标题出现错误

### ISSUE THREAD

**Issue by Only-UU** [Xunzhuo/Coder#13]
大概就如图片这样，不知道是特意这样设计的，还是我写的格式出问题了？
![图片](https://user-images.githubusercontent.com/79325028/108716164-b937a100-7556-11eb-84b5-3a9afdad0ddf.png)
![图片](https://user-images.githubusercontent.com/79325028/108718594-9490f880-7559-11eb-8d41-059ea332542c.png)

**Comment by Only-UU** [comment]
显示成这样
![Uploading 图片.png…]()

**Comment by Xunzhuo** [comment]
markdown 一级、二级标题 只需要在前面加 # 或者 ##呀，后面的 # 和 ##是干嘛的呢？

**Comment by Only-UU** [comment]
呀！挠头，我也不知道，就感觉对称一点看着舒服hhhh我再试试

**Comment by Only-UU** [comment]
它后面对称着来一下好像只是好看，但是把后面给去了，好像还是不行啊
![图片](https://user-images.githubusercontent.com/79325028/108745419-0119f080-7576-11eb-92ed-f235d9156cc1.png)
都是刷新过的，我这篇文章在另一个gitpage上面都可以（另一个主题）
![图片](https://user-images.githubusercontent.com/79325028/108745639-4dfdc700-7576-11eb-8490-224b6cfdd6e6.png)
我其他文章在这个coder主题下的一二级标题（其它的没试）也是会有那个多余的# 符号

**Comment by Xunzhuo** [comment]
现在这种情况是对的，就是这样设计的主题

**Comment by Only-UU** [comment]
啊这，好吧好吧，习惯了还蛮好看的，加油~
