### ISSUE TITLE
点击搜索按钮console显示serch.xml  404

### ISSUE THREAD

**Issue by suyinchuo** [Xunzhuo/Coder#14]
如题,请问作者大大,这个该如何解决,coder2.1版本

**Comment by Xunzhuo** [comment]
@suyinchuo  search.xml 应该会自动生成，像这样：https://github.com/Xunzhuo/xunzhuo.github.io
可以试试重新 hexo g 一下

**Comment by suyinchuo** [comment]
感谢作者!!!安装完成了,非常完美.期待新版本~
