### ISSUE TITLE
uv,pv统计有误

### ISSUE THREAD

**Issue by yyISACoder** [Xunzhuo/Coder#15]
[http://www.carlblog.site](http://www.carlblog.site)，这是我的博客地址，目前我发现uv.pv的统计数会因为我在不同的机器上访问从而产生很大的误差。  
比如我在macbook上访问的时候，统计pv是66，但我用公司电脑访问时就显示600,，这明显是有问题的。
望解决^_^

**Comment by Xunzhuo** [comment]
@yyISACoder  并不是哈，我看了一下 是因为 你在mac上访问的是 http://carlblog.site , 公司访问的是 http://www.carlblog.site，这两个域名前缀是不一样的，一个是@，一个是www

**Comment by yyISACoder** [comment]
> @yyISACoder 并不是哈，我看了一下 是因为 你在mac上访问的是 http://carlblog.site , 公司访问的是 http://www.carlblog.site
> 
> 这两个域名前缀是不一样的，一个是@，一个是www

还有这个区别啊，我以为都是一样的，学习了，感谢^_^

**Comment by yyISACoder** [comment]
> @yyISACoder 并不是哈，我看了一下 是因为 你在mac上访问的是 http://carlblog.site , 公司访问的是 http://www.carlblog.site
> 
> 这两个域名前缀是不一样的，一个是@，一个是www

现在又发现另一个问题，就是uv和pv数量是一样的，不知道是什么原因造成的？

**Comment by Xunzhuo** [comment]
@yyISACoder 你改过源码吗 主题footer

**Comment by yyISACoder** [comment]
> @yyISACoder 你改过源码吗 主题footer

没有改过= =
