### ISSUE TITLE
配置主题时出现“Unhandled rejection TypeError”错误提示

### ISSUE THREAD

**Issue by Raymond-Hear** [Xunzhuo/Coder#18]
您好，请问为什么我在按照readme文件配置后会出现如图的错误提示？
![image](https://user-images.githubusercontent.com/55983690/132443495-be9fe1ee-854a-4467-82eb-c891021d11bf.png)

**Comment by MOZac-hash** [comment]
建议您看下自己的markdown文件头部有没有格式问题，我在使用过程中没有发现过类似问题，同时你也可以试一下重新安装主题

**Comment by Xunzhuo** [comment]
@MOZac-hash 感谢回复 👍 
@Raymond-Hear 可以看看markdown头或者将你的配置文件在这里贴出来看看 🙈

**Comment by Xunzhuo** [comment]
@Raymond-Hear 看看 _config.yaml 的 valine 里的enable是否赋值；最好将你的_config.yaml给贴在这里。
