### ISSUE TITLE
如何增加LiveRe评论功能

### ISSUE THREAD

**Issue by JarlenJohn** [Xunzhuo/Coder#19]
1.在主题的layout下新建livere.ejs文件，存放来必力City版安装代码
```
<!-- 来必力City版安装代码 -->
<div id="lv-container" data-id="city" data-uid="your data-uid">
<script type="text/javascript">
   (function(d, s) {
       var j, e = d.getElementsByTagName(s)[0];

       if (typeof LivereTower === 'function') { return; }

       j = d.createElement(s);
       j.src = 'https://cdn-city.livere.com/js/embed.dist.js';
       j.async = true;

       e.parentNode.insertBefore(j, e);
   })(document, 'script');
</script>
<noscript>为正常使用来必力评论功能请激活JavaScript</noscript>
</div>
<!-- City版安装代码已完成 -->
```
注意上面的your data-uid是自己在来必力注册的用户id

2.post.ejs中添加如下代码：
    <% if (theme.valine.enable){ %>
    <% if (page.comments){ %>
    <%- partial('livere') %>
    <% } else { %>
    <div class="lv-container"></div>
    <% } %>
    <% } %>

3. hexo项目的_config.yml文件下增加以下:
   livere_uid: your data-uid

**Comment by Xunzhuo** [comment]
@JarlenJohn nice, would u like to give a PR to commit these codes?
