### ISSUE TITLE
希望引入Tag Plugins功能！

### ISSUE THREAD

**Issue by necoic** [Xunzhuo/Coder#3]
大佬 我想引用一个styl文件 添加一个相册功能 示例网址 https://jerryc.me/posts/4aa8abbe/#Gallery%E7%9B%B8%E5%86%8A 但我是一个巨白 实在不知道style.styl咋改 请赐教！ 谢谢您嘞。😅😅😅

**Comment by Xunzhuo** [comment]
没太明白你的意思，你是想在这个主题里面添加一个相册功能，还是其他主题？

**Comment by necoic** [comment]
> 没太明白你的意思，你是想在这个主题里面添加一个相册功能，还是其他主题？

https://jerryc.me/photos/ 就是像他这个相册一样的 他是引用了tag plugins这个功能 只要在![]()之前加上{% gallery %}就能自动排列成整齐的照片和预览 ![示例图片](https://s1.ax1x.com/2020/06/22/NGKrS1.png)
